# Generated by Django 5.2 on 2026-04-02 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0002_alter_item_item_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_title',
            field=models.CharField(default='Заголовок', max_length=255, verbose_name='Заголовок (title)'),
        ),
    ]
