# Generated by Django 5.2 on 2026-04-02 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0003_alter_item_item_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_title',
            field=models.CharField(default='Заголовок', help_text='Отображается в теге title страницы и как заголовок контента.', max_length=255, verbose_name='Заголовок (title)'),
        ),
    ]
