# Generated by Django 5.2 on 2026-04-02 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0004_alter_item_item_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_content',
            field=models.TextField(default='<a id="top_of_page" href="#h1" class="card-link">На раздел 1</a>&nbsp;&nbsp;<h6 class="card-subtitle mb-2 text-body-secondary"><a id="h1">Раздел 1</a></h6><p class="card-text">Содержание раздела 1</p><img src="/static/images/settings_django.png" height="30px"><br><a href="#top_of_page" class="card-link">к началу страницы</a>', help_text='HTML-содержимое страницы. Отображается без экранирования (autoescape off).', verbose_name='Основное содержание страницы'),
        ),
    ]
