# Generated by Django 5.2 on 2026-04-02 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0005_alter_item_item_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ('item_nav_position',), 'verbose_name': 'Страница', 'verbose_name_plural': 'Страницы'},
        ),
    ]
