# Generated by Django 5.2 on 2026-04-02 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0006_alter_item_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_content',
            field=models.TextField(default='<a id="top_of_page" href="#h1" class="card-link">На раздел 1</a>&nbsp;&nbsp;<h6 class="card-subtitle mb-2 text-body-secondary"><a id="h1">Раздел 1</a></h6><p class="card-text">Содержание раздела 1</p><img src="/static/images/settings_django.png" height="30px"><br><a href="#top_of_page" class="card-link">к началу страницы</a>', help_text='HTML-содержимое страницы. Отображается без экранирования (autoescape off).', verbose_name='Содержание страницы'),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_nav',
            field=models.CharField(default='Название ссылки', help_text='Текст, отображаемый в навигационном меню.', max_length=255, verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_nav_position',
            field=models.IntegerField(default=1, help_text='Чем больше число — тем правее ссылка. 0 — скрыть из навигации.', verbose_name='НавигПриорит(0—Искл)'),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_title',
            field=models.CharField(default='Заголовок', help_text='Отображается в теге title страницы и как заголовок контента.', max_length=255, verbose_name='title'),
        ),
    ]
